module.exports.cmdSwitch = function (category) {
    switch (category) {
        case 'allencyclopedia':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?size=3000';
        case 'allequipments':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?size=3000';
        case 'helmet':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=16&size=500';
        case 'cloak':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=17&size=500';
        case 'amulet':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id[0]=1&size=500';
        case 'boot':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=11&size=500';
        case 'ring':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=9&size=500';
        case 'belt':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=10&size=500';
        case 'backpack':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=81&size=500';
        case 'shield':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=82&size=500';
        case 'trophy':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=151&size=500';
        case 'dofus':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?text=&type_id%5B%5D=23&size=500';
        case 'allweapons':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?size=3000';
        case 'sword':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=6&size=500';
        case 'dagger':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=5&size=500';
        case 'axe':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=19&size=500';
        case 'bow':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=2&size=500';
        case 'hammer':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=7&size=500';
        case 'pickaxe':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=21&size=500';
        case 'scythe':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=22&size=500';
        case 'shovel':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=8&size=500';
        case 'soulstone':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=83&size=500';
        case 'staff':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=4&size=500';
        case 'tool':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=20&size=500';
        case 'wand':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/armes?text=&type_id[]=3&size=500';
        case 'sets':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/panoplies?size=500';
        case 'mounts':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/montures?size=500';
        case 'pets':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/familiers?size=500';
        case 'resources':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/ressources?size=3000';
        case 'consumables':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/consommables?size=3000';
        case 'professions':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/metiers?size=500&display=table';
        case 'monsters':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/monstres?size=3000';
        case 'harnesses':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/harnachements?size=150';
        case 'classes':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/classes';
        case 'idols':
            return 'https://www.dofus.com/fr/mmorpg/encyclopedie/idoles?size=100';
        default:
            console.log('Sorry, we are out of ' + category + '.');
    }
    return '';
};

module.exports.cmdSwitchEn = function (category) {
    switch (category) {
        case 'allencyclopedia':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?size=3000';
        case 'allequipments':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?size=3000';
        case 'helmet':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=16&size=500';
        case 'cloak':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=17&size=500';
        case 'amulet':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id[0]=1&size=500';
        case 'boot':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=11&size=500';
        case 'ring':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=9&size=500';
        case 'belt':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=10&size=500';
        case 'backpack':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=81&size=500';
        case 'shield':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=82&size=500';
        case 'trophy':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=151&size=500';
        case 'dofus':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/equipment?text=&type_id%5B%5D=23&size=500';
        case 'allweapons':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?size=3000';
        case 'sword':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=6&size=500';
        case 'dagger':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=5&size=500';
        case 'axe':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=19&size=500';
        case 'bow':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=2&size=500';
        case 'hammer':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=7&size=500';
        case 'pickaxe':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=21&size=500';
        case 'scythe':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=22&size=500';
        case 'shovel':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=8&size=500';
        case 'soulstone':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=83&size=500';
        case 'staff':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=4&size=500';
        case 'tool':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=20&size=500';
        case 'wand':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/weapons?text=&type_id[]=3&size=500';
        case 'sets':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/sets?size=500';
        case 'mounts':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/mounts?size=500';
        case 'pets':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/pets?size=500';
        case 'resources':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/resources?size=3000';
        case 'consumables':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/consumables?size=3000';
        case 'professions':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/professions?size=500&display=table';
        case 'monsters':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/monsters?size=3000';
        case 'harnesses':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/harnesses?size=150';
        case 'classes':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/classes';
        case 'idols':
            return 'https://www.dofus.com/en/mmorpg/encyclopedia/idols?size=100';
        default:
            console.log('Sorry, we are out of ' + category + '.');
    }
    return '';
};
